CREATE TABLE public.facts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  text text NULL,
  source text NULL,
  category text NULL,
  "votesInteresting" integer NULL DEFAULT 0,
  "votesMindblowing" integer NULL DEFAULT 0,
  "votesFalse" integer NULL DEFAULT 0,
  CONSTRAINT facts_pkey PRIMARY KEY (id)
);
ALTER TABLE public.facts ENABLE ROW LEVEL SECURITY;